### ISSUE TITLE
Homepage rendering fails when hard deadline is not set

### ISSUE THREAD

**Issue by mgax** [vmck/acs-interface#107]
```
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/interface/interface/views.py", line 102, in homepage
    'logout_url': redirect(logout_view).url,
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/defaulttags.py", line 302, in render
    match = condition.eval(context)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/defaulttags.py", line 876, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/root/.local/share/virtualenvs/interface-yvgcbbav/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/opt/interface/interface/models.py", line 51, in is_active
    diff = self.deadline_hard - now
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'
```

**Comment by Jokeswar** [comment]
`null=true` should be removed from https://github.com/vmck/acs-interface/blob/master/interface/models.py#L42-L43
